### ISSUE TITLE
Format option in datepicker-bs4 does NOT work?

### ISSUE THREAD

**Issue by MicJarek** [lesilent/datepicker-bs4#1]
Nice little Bootstrap addon date picker (clean, fast, and looks great), but I'm having problems with setting a custom date format display when a date is selected. According to instructions in: https://www.jqueryscript.net/time-clock/bootstrap-date-picker-dayjs.html, it's a matter of setting the format option (i.e. format: 'MM/DD/YYYY'), but it doesn't seem to work.

If no 'format' is specified, the picker populates the field correctly in the format: 'mm/dd/yyyy'. BUT when I try to set any other format (i.e. 'YYYY/MM/DD'), a date selection no longer populates the edit field because it appears that the parseDate(this.value, input_options) fails and returns false (from what I can see in the debugger).

Any suggestions on how to fix this?
I'm using Bootstrap 4.6.0.

**Comment by lesilent** [comment]
The bug should be fixed now in the newest commit.

**Comment by MicJarek** [comment]
Yes... the formatting is fixed and works great now. Tks.

On a side note... I wasn't sure about opening up another issue for an enhancement request so I thought I'd ask here.

Have you considered also adding a timepicker to the lib? There is a really cool slider version of this at https://www.jqueryscript.net/time-clock/Time-Picker-jQuery-UI-Datepicker.html BUT it is no longer maintained. So I thought maybe it can be easily incorporated into this addon. I'm sure others would also appreciate the added feature because in many cases users need to also select a time along with a date.

Just a thought... :)

**Comment by lesilent** [comment]
IMHO, I'm not a fan of combined date and time pickers. I think having to select both date and time in the same input field is a bit confusing to users. I'd rather have separate date and input fields, and then separate date and time pickers to go with them. That gives you the flexibility to use different pickers for each, or have complicated logic like where the time selection is dependent on the date (eg. 9am-5pm Mon-Fri, but 10am-4pm Sat-Sun).   

My plan is to eventually create a separate time picker at some point.

**Comment by MicJarek** [comment]
I see your point and completely agree. In fact, I'm doing just that in my current app: keeping the 2 separate. I just happen to run across the above mentioned timepicker example and thought it was quite intuitive, clean, and simple for the user to use the sliders to select the time (I'm not a big fan of DropDown hours/minutes selection). Unfortunately that slider code doesn't seem to jive well with BS4 (responsiveness, etc.).

Anyway, thanks for the format fix and let me know when you get to the timepicker... I would love to test it out and possibly use it in the app.

**Comment by lesilent** [comment]
I've just added a [timepicker](https://github.com/lesilent/timepicker-bs4/) if you're interested in testing it out for possible use.
