### ISSUE TITLE
Date format not working on mobile

### ISSUE THREAD

**Issue by MicJarek** [lesilent/datepicker-bs4#2]
Hi Lesilent,

The datepicker works great when in full browser mode, but when you run the same code on a mobile device (or even the emulator in Edge: i.e. select the 3-dots Setting and More to display the menu and then select More Tools | Developer Tools | and click the Toggle Device Emulation), it looks like the default browser date picker appears instead of the datepicker-bs4.

You can see this also happening on your demo page. Make sure that when you run the emulation mode, you need to refresh the page to reset the control to display the issue (if you just toggle the emulator option on, it will display the mask and datepicker-bs4 correctly).

Anyway, I've been using the datepicker-bs4 for a while in development and just noticed this since I'm finally to the point of production ready. Is this something with the browser/bootstrap or the datepicker-bs4 needs to be tweaked?

Tks... :)

**Comment by lesilent** [comment]
This was due to the minScreenWidth option that has a default of 576 pixels. That means any screen widths less than that would use the browser's native date picker instead. I've removed this option from the new version, so it should work on a mobile device now.
